require('dotenv').config();

module.exports = {
    BOT_TOKEN: process.env.BOT_TOKEN || '',
    OWNER_ID: process.env.OWNER_ID ? parseInt(process.env.OWNER_ID) : 0,
    OPENAI_KEY: process.env.OPENAI_KEY || '',
    REMOVEBG_KEY: process.env.REMOVEBG_KEY || '',
    BOT_NAME: 'Multi Bot',
    VERSION: '1.0.0',
    PREFIX: '/',
    WELCOME_IMAGE: './assets/welcome.jpg',
    WELCOME_AUDIO: './assets/welcome.mp3',
    COOLDOWN: 5000,
    PREMIUM_USERS: [],
    MENUS: {
        'AI': '🤖 AI Menu',
        'PINTEREST': '📌 Pinterest Menu',
        'PLAY': '🎵 Play Menu',
        'REMINI': '✨ Remini Menu',
        'REMOVEBG': '🖼️ RemoveBG Menu',
        'MAKER': '🎨 Maker Menu',
        'DOWNLOAD': '⬇️ Download Menu',
        'SEARCH': '🔍 Search Menu',
        'STALK': '🕵️ Stalk Menu',
        'TOOLS': '🛠️ Tools Menu',
        'GAME': '🎮 Game Menu',
        'FUN': '😄 Fun Menu',
        'OWNER': '👑 Owner Menu',
        'JAGAGRUP': '🛡️ Jaga Grup Menu',
        'FAMILY100': '👨‍👩‍👧 Family 100 Menu',
        'FF': '🎯 Krakter FF Menu',
        'STORE': '🏪 Store Menu',
        'INFO': 'ℹ️ Info Menu',
        'HDFOTO': '📸 HD Foto Menu',
        'TOURL': '🔗 ToURL Menu',
        'BROADCAST': '📢 Broadcast Menu',
        'BRAT': '💬 Brat Menu',
        'VPS': '💻 VPS Menu',
        'DOMAIN': '🌐 Domain Menu',
        'PRODUK': '📦 Produk Menu',
        'CPANEL': '⚙️ cPanel Menu',
        'IMAGEWELCOME': '🖼️ Image Welcome Menu',
        'OBF': '🔒 OBF Menu',
        'PTRO': '🎨 PTRO Menu',
        'HOYO': '⚔️ Hoyo Menu',
        'ISLAMIC': '🕌 Islamic Menu',
        'CERPEN': '📖 Cerpen Menu',
        'CONVERT': '🔄 Convert Menu'
    }
};
